/**
 * This file is auto-generated by Supabase CLI
 * Run: npm run db:generate
 * 
 * For now, manually defined types based on schema
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type DeliveryMethod = 'external_link' | 'drive_integration'
export type JobStatus = 'Inquiry' | 'Booked' | 'Shooting' | 'Editing' | 'Review' | 'Delivered' | 'Completed' | 'Cancelled'
export type InvoiceStatus = 'Draft' | 'Sent' | 'Paid' | 'Partially Paid' | 'Overdue' | 'Cancelled'
export type PaymentStatus = 'Pending' | 'Completed' | 'Failed' | 'Refunded'
export type PaymentType = 'Deposit' | 'Final' | 'Refund'
export type PaymentMethod = 'Stripe' | 'PayPal' | 'Cash' | 'Check' | 'Bank Transfer'
export type TaskPriority = 'Low' | 'Medium' | 'High'
export type CloudProvider = 'Google' | 'Dropbox' | 'OneDrive' | 'None'
export type IntegrationProvider = 'google' | 'dropbox'

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          avatar_url: string | null
          branding_logo: string | null
          branding_primary_color: string
          branding_secondary_color: string
          user_type: 'freelancer' | 'company' | null
          date_of_birth: string | null
          company_name: string | null
          role: 'super_admin' | 'admin' | 'user'
          status: 'pending' | 'active' | 'suspended' | 'rejected'
          approved_by: string | null
          approved_at: string | null
          rejection_reason: string | null
          profile_setup_completed: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          name?: string | null
          avatar_url?: string | null
          branding_logo?: string | null
          branding_primary_color?: string
          branding_secondary_color?: string
          user_type?: 'freelancer' | 'company' | null
          date_of_birth?: string | null
          company_name?: string | null
          role?: 'super_admin' | 'admin' | 'user'
          status?: 'pending' | 'active' | 'suspended' | 'rejected'
          approved_by?: string | null
          approved_at?: string | null
          rejection_reason?: string | null
          profile_setup_completed?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          avatar_url?: string | null
          branding_logo?: string | null
          branding_primary_color?: string
          branding_secondary_color?: string
          created_at?: string
          user_type?: 'freelancer' | 'company' | null
          date_of_birth?: string | null
          company_name?: string | null
          role?: 'super_admin' | 'admin' | 'user'
          status?: 'pending' | 'active' | 'suspended' | 'rejected'
          approved_by?: string | null
          approved_at?: string | null
          rejection_reason?: string | null
          profile_setup_completed?: boolean
          updated_at?: string
        }
      }
      clients: {
        Row: {
          id: string
          user_id: string
          name: string
          email: string | null
          phone: string | null
          company: string | null
          address: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          email?: string | null
          phone?: string | null
          company?: string | null
          address?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          email?: string | null
          phone?: string | null
          company?: string | null
          address?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      jobs: {
        Row: {
          id: string
          user_id: string
          client_id: string
          title: string | null
          date: string
          start_time: string | null
          end_time: string | null
          timezone: string
          location: string | null
          package_type: string | null
          status: JobStatus
          price: number
          deposit_amount: number | null
          notes: string | null
          shot_list: Json
          gear_checklist: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          client_id: string
          title?: string | null
          date: string
          start_time?: string | null
          end_time?: string | null
          timezone?: string
          location?: string | null
          package_type?: string | null
          status?: JobStatus
          price: number
          deposit_amount?: number | null
          notes?: string | null
          shot_list?: Json
          gear_checklist?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          client_id?: string
          title?: string | null
          date?: string
          start_time?: string | null
          end_time?: string | null
          timezone?: string
          location?: string | null
          package_type?: string | null
          status?: JobStatus
          price?: number
          deposit_amount?: number | null
          notes?: string | null
          shot_list?: Json
          gear_checklist?: Json
          created_at?: string
          updated_at?: string
        }
      }
      invoices: {
        Row: {
          id: string
          job_id: string
          invoice_number: string
          total_amount: number
          paid_amount: number
          balance: number
          due_date: string | null
          status: InvoiceStatus
          pdf_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          job_id: string
          invoice_number?: string
          total_amount: number
          paid_amount?: number
          due_date?: string | null
          status?: InvoiceStatus
          pdf_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          job_id?: string
          invoice_number?: string
          total_amount?: number
          paid_amount?: number
          due_date?: string | null
          status?: InvoiceStatus
          pdf_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      payments: {
        Row: {
          id: string
          invoice_id: string | null
          job_id: string
          amount: number
          type: PaymentType | null
          status: PaymentStatus
          date: string
          method: PaymentMethod | null
          transaction_id: string | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          invoice_id?: string | null
          job_id: string
          amount: number
          type?: PaymentType | null
          status?: PaymentStatus
          date: string
          method?: PaymentMethod | null
          transaction_id?: string | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          invoice_id?: string | null
          job_id?: string
          amount?: number
          type?: PaymentType | null
          status?: PaymentStatus
          date?: string
          method?: PaymentMethod | null
          transaction_id?: string | null
          notes?: string | null
          created_at?: string
        }
      }
      expenses: {
        Row: {
          id: string
          job_id: string
          category: string
          amount: number
          date: string
          notes: string | null
          receipt_url: string | null
          created_at: string
        }
        Insert: {
          id?: string
          job_id: string
          category: string
          amount: number
          date: string
          notes?: string | null
          receipt_url?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          job_id?: string
          category?: string
          amount?: number
          date?: string
          notes?: string | null
          receipt_url?: string | null
          created_at?: string
        }
      }
      tasks: {
        Row: {
          id: string
          job_id: string
          description: string
          due_date: string | null
          assigned_to: string | null
          is_done: boolean
          priority: TaskPriority
          created_at: string
          completed_at: string | null
        }
        Insert: {
          id?: string
          job_id: string
          description: string
          due_date?: string | null
          assigned_to?: string | null
          is_done?: boolean
          priority?: TaskPriority
          created_at?: string
          completed_at?: string | null
        }
        Update: {
          id?: string
          job_id?: string
          description?: string
          due_date?: string | null
          assigned_to?: string | null
          is_done?: boolean
          priority?: TaskPriority
          created_at?: string
          completed_at?: string | null
        }
      }
      team_members: {
        Row: {
          id: string
          job_id: string
          user_id: string
          role: string | null
          access_level: string
          created_at: string
        }
        Insert: {
          id?: string
          job_id: string
          user_id: string
          role?: string | null
          access_level?: string
          created_at?: string
        }
        Update: {
          id?: string
          job_id?: string
          user_id?: string
          role?: string | null
          access_level?: string
          created_at?: string
        }
      }
      deliverables: {
        Row: {
          id: string
          job_id: string
          method: DeliveryMethod
          external_url: string | null
          drive_folder_id: string | null
          provider: CloudProvider | null
          is_locked: boolean
          password: string | null
          expires_at: string | null
          download_count: number
          access_log: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          job_id: string
          method: DeliveryMethod
          external_url?: string | null
          drive_folder_id?: string | null
          provider?: CloudProvider | null
          is_locked?: boolean
          password?: string | null
          expires_at?: string | null
          download_count?: number
          access_log?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          job_id?: string
          method?: DeliveryMethod
          external_url?: string | null
          drive_folder_id?: string | null
          provider?: CloudProvider | null
          is_locked?: boolean
          password?: string | null
          expires_at?: string | null
          download_count?: number
          access_log?: Json
          created_at?: string
          updated_at?: string
        }
      }
      integrations: {
        Row: {
          id: string
          user_id: string
          provider: IntegrationProvider
          access_token: string
          refresh_token: string | null
          expires_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          provider: IntegrationProvider
          access_token: string
          refresh_token?: string | null
          expires_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          provider?: IntegrationProvider
          access_token?: string
          refresh_token?: string | null
          expires_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      delivery_method: DeliveryMethod
    }
  }
}

